# Generated by Django 4.1 on 2022-08-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='code-solid.svg', null=True, upload_to='images'),
        ),
    ]
