# Generated by Django 4.1 on 2022-08-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='social_githup',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
