# Generated by Django 4.1 on 2022-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_home_social_facebook_alter_home_social_githup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, default='programmer-icon-4.svg', null=True, upload_to='images'),
        ),
    ]
