# Generated by Django 4.1 on 2022-08-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('project_githup', models.CharField(blank=True, max_length=400, null=True)),
                ('social_live', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(blank=True, default='p-2.png', null=True, upload_to='images')),
            ],
        ),
    ]
