# Generated by Django 4.1 on 2022-08-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_featured_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured_project',
            old_name='social_live',
            new_name='project_live',
        ),
    ]
