# Generated by Django 4.1 on 2022-08-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_technical_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technical_Skills',
            new_name='Technical_Skill',
        ),
    ]
