# Generated by Django 4.1 on 2022-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_education_work_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('project_githup', models.CharField(blank=True, max_length=400, null=True)),
                ('project_live', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(blank=True, default='g1.jpg', null=True, upload_to='images')),
                ('screenshot_1', models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images')),
                ('screenshot_1_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('screenshot_2', models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images')),
                ('screenshot_2_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('tags', models.ManyToManyField(null=True, to='main.tag')),
            ],
        ),
    ]
