# Generated by Django 4.1 on 2022-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_project_screenshot_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot_1',
            field=models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_2',
            field=models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images'),
        ),
    ]
