# Generated by Django 4.1 on 2022-08-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_project_screenshot_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_githup',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_live',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot_1_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot_2_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('project_githup', models.CharField(blank=True, max_length=400, null=True)),
                ('project_live', models.CharField(blank=True, max_length=400, null=True)),
                ('screenshot_1', models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images')),
                ('screenshot_1_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('screenshot_2', models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images')),
                ('screenshot_2_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('tags', models.ManyToManyField(null=True, to='main.tag')),
            ],
        ),
    ]
