# Generated by Django 4.1 on 2022-08-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_detail',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
