# Generated by Django 4.1 on 2022-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_project_detail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_githup',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_live',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_1',
            field=models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_1_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_2',
            field=models.ImageField(blank=True, default='pr-0.jif', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_2_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(null=True, to='main.tag'),
        ),
        migrations.DeleteModel(
            name='Project_Detail',
        ),
    ]
