# Generated by Django 4.1 on 2022-08-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contactprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactProfile',
        ),
    ]
