# Generated by Django 4.1 on 2022-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
