# Generated by Django 4.1 on 2022-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_project',
            name='image',
            field=models.ImageField(blank=True, default='project_defult.svg', null=True, upload_to='images'),
        ),
    ]
