# Generated by Django 4.1 on 2022-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='programmer-icon-defult-min.svg', null=True, upload_to='images'),
        ),
    ]
