# Generated by Django 4.1 on 2022-08-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.URLField(blank=True, default='https://cdn2.iconfinder.com/data/icons/picol-vector/32/source_code-256.png', max_length=400, null=True),
        ),
    ]
