# Generated by Django 4.1 on 2022-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.URLField(blank=True, default='https://imgur.com/LWbrALG', max_length=400, null=True),
        ),
    ]
