# Generated by Django 4.1 on 2022-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.URLField(blank=True, default='https://cdn.iconfinder.com/stored_data/565757/128/png?token=1661633065-WLsZtBOURCWRzxfAdPaxjVdZh7jGDN2DQPJDoQgKOB4%3D', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.URLField(blank=True, default='https://cdn.iconfinder.com/stored_data/565757/128/png?token=1661633065-WLsZtBOURCWRzxfAdPaxjVdZh7jGDN2DQPJDoQgKOB4%3D', max_length=400, null=True),
        ),
    ]
