# Generated by Django 4.1 on 2022-08-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_about_image_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.URLField(blank=True, default='https://cdn.iconfinder.com/icons/756828/1180798/512/raster.png?token=1661633464-S9fW9iHPH6n7KyNbpRKBv6x4k6kwuDoitM7HPVGgkg0%3D', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='featured_project',
            name='image',
            field=models.URLField(blank=True, default='https://cdn3.iconfinder.com/data/icons/seo-marketing-19/32/SEO-13-512.png', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.URLField(blank=True, default='https://cdn.iconfinder.com/icons/756828/1180798/512/raster.png?token=1661633464-S9fW9iHPH6n7KyNbpRKBv6x4k6kwuDoitM7HPVGgkg0%3D', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='https://cdn3.iconfinder.com/data/icons/seo-marketing-19/32/SEO-13-512.png', max_length=400, null=True),
        ),
    ]
