# Generated by Django 4.1 on 2022-08-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_about_image_alter_featured_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
