# Generated by Django 4.1 on 2022-08-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, default='programmer-icon-defult-min.svg', max_length=400, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default='programmer-icon-defult-min.svg', max_length=400, null=True, upload_to=''),
        ),
    ]
