# Generated by Django 4.1 on 2022-08-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_home_image_alter_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
