# Generated by Django 4.1 on 2022-08-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_about_image_remove_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_project',
            name='image',
            field=models.URLField(blank=True, default='https://cdn4.iconfinder.com/data/icons/thin-line-icons-for-seo-and-development-1/64/seo_programming-512.png', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='https://cdn4.iconfinder.com/data/icons/thin-line-icons-for-seo-and-development-1/64/seo_programming-512.png', max_length=400, null=True),
        ),
    ]
