# Generated by Django 4.1 on 2022-08-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_featured_project_image_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='https://cdn3.iconfinder.com/data/icons/network-and-communications-10/32/network_code_coding_web_web_page_programming-512.png', max_length=400, null=True),
        ),
    ]
