# Generated by Django 4.1 on 2022-08-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot_1',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_2',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
